In [2]:
import numpy as np 

## Numpy Broadcasting 

In [4]:
# meshgrid tạo ra mảng 2 chiều
X,Y = np.meshgrid(np.arange(2), np.arange(2))

print (X)
print(Y)
print(X + Y)

[[0 1]
 [0 1]]
[[0 0]
 [1 1]]
[[0 1]
 [1 2]]


In [6]:
# add broadcast dimension 
X[:, None] + Y

array([[[0, 1],
        [1, 2]],

       [[0, 1],
        [1, 2]]])